### ISSUE TITLE
能否提供生成单个头像的api

### ISSUE THREAD

**Issue by axipo** [Codennnn/vue-color-avatar#12]
比如`/api/avatar?config=urlencoded(configObject)`，这样就可以方便嵌入到论坛及博客系统里面。生成的文件可以用svg格式，也可以后端渲染为位图格式。涉及到后端可能与本项目原始定位有点偏离，但感觉是个较为实用的feature。

**Comment by Codennnn** [comment]
这个项目其实是以个人小站部署在 vercel 上的，如果提供第三方 API 供人使用的话，体验会很差。目前我不打算继续扩展这样的功能，如果你感兴趣的话，可以提个 PR 来完善，或者 fork 来开展你想要的功能。

**Comment by axipo** [comment]
@Codennnn 明白了，我看了下这个项目的源码，然后已经自己撸了一个后端渲染版本并实地应用了，谢谢

**Comment by ijrou** [comment]
> @Codennnn 明白了，我看了下这个项目的源码，然后已经自己撸了一个后端渲染版本并实地应用了，谢谢

Can you share?

**Comment by 13627491210** [comment]
> @Codennnn 明白了，我看了下这个项目的源码，然后已经自己撸了一个后端渲染版本并实地应用了，谢谢

大佬，方便提供一下接口或者代码参考吗？我也有这个需求，谢谢
