### ISSUE TITLE
The feature randomize and generate multiple don't randomize the skin tone

### ISSUE THREAD

**Issue by fabioooliveira** [Codennnn/vue-color-avatar#13]
When using the randomize or generate multiples features, the generated avatar randomizes all parameters of an avatar, except the skin tone.
We have three skin tones defined in the template (still too few but more on that later), the script should apply one of the three to the `base` element every random avatar generation.

**Context**
In Brazil, we have a very mixed population, generating a huge variety of skin tones. This tweak would make the template more interesting for designers working in Brazilian companies as it would better represent the Brazilian population.

**Comment by iondrimba-fb** [comment]
+1

**Comment by Codennnn** [comment]
Makes sense, I'll be adding this feature soon.

**Comment by Codennnn** [comment]
Multiple skin tones are now supported!

**Comment by iondrimba-fb** [comment]
Thank you @Codennnn :clap: :clap: :clap: :clap: :clap: :clap: :clap: :clap: :clap: :clap: :clap: :clap: :clap: :clap: :clap: :clap: :clap: :clap: :clap: :clap: :clap: :clap: :clap: :clap: :clap: :clap: :clap: :clap: :clap: :clap:
