### ISSUE TITLE
胡子不能过滤嘴巴和牙齿，导致胡子长在了嘴里

### ISSUE THREAD

**Issue by xhatt** [Codennnn/vue-color-avatar#2]

**Comment by gaoryrt** [comment]
Still got this problem
![image](https://user-images.githubusercontent.com/5306513/163505540-04e02484-07ef-4b66-81b9-0b7e6f66362b.png)

**Comment by Codennnn** [comment]
> Still got this problem, great work though ![image](https://user-images.githubusercontent.com/5306513/163505540-04e02484-07ef-4b66-81b9-0b7e6f66362b.png)

已修复。
