### ISSUE TITLE
Feature request: Customizing colors for components

### ISSUE THREAD

**Issue by gaoryrt** [Codennnn/vue-color-avatar#8]
As titled, need more color for hair.

**Comment by Codennnn** [comment]
已新增对头发和衣服颜色选择的功能。

**Comment by Codennnn** [comment]
> 

已新增对头发和衣服颜色选择的功能。

**Comment by Codennnn** [comment]
> As titled, need more color for hair.

已新增对头发和衣服颜色选择的功能。
